name: macOS NR Agent Install
on: workflow_dispatch
jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - name: Run New Relic CLI
        run: |
               curl -Ls https://download.newrelic.com/install/newrelic-cli/scripts/install.sh
